#!/bin/bash
#
# https://github.com/DieNacht/autoremove-torrents-installation
# Author: DieNacht
#
# Thanks to amefs and Aniverse

ln -s $(which autoremove-torrents) /usr/local/bin/art

cat << 'EOF' > /usr/local/bin/art-execute
$(which autoremove-torrents) -c $HOME/.config/autoremove-torrents/config.yml -l $HOME/.config/autoremove-torrents/logs
EOF
chmod +x /usr/local/bin/art-execute

cat << 'EOF' > /usr/local/bin/art-configure
[[ $HOME != "/root" ]] && pm="sudo apt" || pm="apt"
[ -z $(which nano) ] && $pm update && $pm -y install nano
[ $? = 1 ] && exit 1
$(which nano) $HOME/.config/autoremove-torrents/config.yml
EOF
chmod +x /usr/local/bin/art-configure
