# For more usages, check the offical site: https://autoremove-torrents.readthedocs.io/zh_CN/latest/

# client templates
# deluge:
#   client: deluge
#   host: 127.0.0.1:$de_port
#   username: $iUser
#   password: $iPass
# qbittorrent:
#   client: qbittorrent
#   host: http://127.0.0.1:$qb_port
#   username: $iUser
#   password: $iPass
# transmission:
#   client: transmission
#   host: http://127.0.0.1:$tr_port
#   username: $iUser
#   password: $iPass

Example1:
  client: deluge
  host: 127.0.0.1:$de_port                                     # No "http://" or "https://"
  username: $iUser
  password: $iPass
  strategies:
    delete_by_seedsize:
      trackers:
        - tracker.hdsky.me                                     # No "http://" or "https://"
      seed_size:
        limit: 3000                                            # Count in GiB
        action: remove-old-seeds
    delete_by_seedtime:
      categories:
        - hdsky
      seeding_time: 259200                                     # Count in Second
  delete_data: true

Example2:
  client: qbittorrent
  host: http://127.0.0.1:$qb_port
  username: $iUser
  password: $iPass
  strategies:
    delete_by_restspace:
      free_space:
        min: 100                                               # Count in GiB
        path: $iHome                                  # This Path MUST EXIST
        action: remove-old-seeds
    delete_by_peernumber:
      status:
        - Downloading
      remove: connected_leecher < 2 or seeder > 1
    delete_by_speed:
      status:
        - Downloading
      remove: download_speed > 20480 and upload_speed < 20480  # Count in KiB per Second
  delete_data: true

Example3:
  client: transmission
  host: http://127.0.0.1:$tr_port
  username: $iUser
  password: $iPass
  strategies:
    delete_by_crosscheck:
      status:
        - Checking
      remove: progress > 1                                     # Count in Percentage(%)
  delete_data: false