#!/bin/bash
#
# https://github.com/DieNacht/autoremove-torrents-installation
# Author: DieNacht
#
# Thanks to amefs and Aniverse

unset LogRootPath LogTimes DebLocation SCLocation LOCKLocation OutputLOG \
      user

AppName="AutoRemove-Torrents"
AppNameLower="autoremove-torrents"
Need_SourceCode=no
pm_action=install

if [[ -f /etc/inexistence/00.Installation/function ]]; then
    source /etc/inexistence/00.Installation/function
else
    source <(wget -qO- https://github.com/Aniverse/inexistence/raw/master/00.Installation/function)
fi

set_variables_log_location
check_var_OutputLOG
debug_log_location
cat_outputlog

function install_art() {

    echo >> $OutputLOG

    if [[ "$CODENAME" == xenial ]]; then
        apt_install_check    python3.6-psutil
        apt_install_separate
    elif [[ "$CODENAME" =~ (bionic|buster) ]]; then
        apt_install_check    python3-psutil
        apt_install_separate
    fi

    wget -nv -O get-pip.py https://bootstrap.pypa.io/get-pip.py >> "$OutputLOG" 2>&1
    python3 get-pip.py --force-reinstall                        >> "$OutputLOG" 2>&1
    pip3 install --upgrade pip                                  >> "$OutputLOG" 2>&1
    pip3 install setuptools==45.3.0                             >> "$OutputLOG" 2>&1

    pip3 install --upgrade pyopenssl                            >> "$OutputLOG" 2>&1
    pip3 install --upgrade cryptography                         >> "$OutputLOG" 2>&1
    pip3 install --ignore-installed autoremove-torrents         >> "$OutputLOG" 2>&1

    status_lock=$AppNameLower
    echo "status_lock=$status_lock" > /tmp/Variables
    rm -f /tmp/$status_lock.1.lock /tmp/$status_lock.2.lock 
    # if [[ -n $(which autoremove-torrents) ]]; then
    if version_ge $(autoremove-torrents -v -l /tmp 2>&1 | head -1 | grep -oP "[0-9.]+" | tail -1) 1.5.2 ; then
        touch /tmp/$status_lock.1.lock
    else
        touch /tmp/$status_lock.2.lock
    fi
    [[ -f /tmp/$status_lock.1.lock ]] && touch $LOCKLocation/$AppNameLower.lock
    echo >> $OutputLOG

}

if [[ ! -f $LOCKLocation/python3.lock ]]; then
    bash <(wget -qO- https://github.com/Aniverse/inexistence/raw/master/00.Installation/package/python) --tmp
fi

echo_task "Installing $AppName ..."
install_art & spinner $!
check_status $status_lock
