#!/bin/bash
#
# https://github.com/DieNacht/autoremove-torrents-installation
# Author: DieNacht
#
# Thanks to amefs and Aniverse

unset LogRootPath LogTimes DebLocation SCLocation LOCKLocation OutputLOG \
      user

AppName="AutoRemove-Torrents"
AppNameLower="autoremove-torrents"
Need_SourceCode=no
pm_action=install

if [[ -f /etc/inexistence/00.Installation/function ]]; then
    source /etc/inexistence/00.Installation/function
else
    source <(wget -qO- https://github.com/Aniverse/inexistence/raw/master/00.Installation/function)
fi

set_variables_log_location
check_var_OutputLOG
debug_log_location
cat_outputlog

function install_python37() {
    pyenv_install_python 3.7.8
    pyenv_init_venv      3.7.8   /opt/venv/flexget
    python_getpip        3.7.8   /opt/venv/flexget
    pip_cmd="/opt/venv/flexget/bin/pip"
    python_cmd="/opt/venv/flexget/bin/python"
}

function install_art() {

    echo >> $OutputLOG

    $pip_cmd install --upgrade setuptools                           >> "$OutputLOG" 2>&1
    $pip_cmd install --upgrade pyopenssl                            >> "$OutputLOG" 2>&1
    $pip_cmd install --upgrade cryptography                         >> "$OutputLOG" 2>&1
    $pip_cmd install autoremove-torrents                            >> "$OutputLOG" 2>&1

    rm -f /usr/local/bin/autoremove-torrents                        >> "$OutputLOG" 2>&1
    ln -s /opt/venv/flexget/bin/autoremove-torrents\
    /usr/local/bin/autoremove-torrents                              >> "$OutputLOG" 2>&1

    status_lock=$AppNameLower
    echo "status_lock=$status_lock" > /tmp/Variables
    rm -f /tmp/$status_lock.1.lock /tmp/$status_lock.2.lock 
    # if [[ -n $(which autoremove-torrents) ]]; then
    if [[ ! $(which autoremove-torrents) == "" ]] && version_ge $($(which autoremove-torrents) -v -l /tmp 2>&1 | head -1 | grep -oP "[0-9.]+" | tail -1) 1.5.2 ; then
        touch /tmp/$status_lock.1.lock
    else
        touch /tmp/$status_lock.2.lock
    fi
    [[ -f /tmp/$status_lock.1.lock ]] && touch $LOCKLocation/$AppNameLower.lock
    echo >> $OutputLOG

}

if [[ ! -f $LOCKLocation/pyenv.lock ]]; then
    bash <(wget -qO- https://github.com/Aniverse/inexistence/raw/master/00.Installation/package/pyenv)
fi

install_python37

echo_task "Installing $AppName ..."
install_art & spinner $!
check_status $status_lock
